using Microsoft.ML.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nerdostat.Device.Models
{
    public class MLModels
    {
        public class InputData
        {
            public float temperature { get; set; }

            public float month { get; set; }
            public float day { get; set; }
            public float hour { get; set; }

            //public float humidity { get; set; }
            //public float heaterStatus { get; set; }

            public float tempLag1 { get; set; }
            public float tempLag2 { get; set; }
            public float tempLag3 { get; set; }
            public float tempLag4 { get; set; }
            public float tempLag5 { get; set; }
            public float tempLag6 { get; set; }
            public float tempLag7 { get; set; }
            public float tempLag8 { get; set; }
            public float tempLag9 { get; set; }
            public float tempLag10 { get; set; }
            public float tempLag11 { get; set; }
            public float tempLag12 { get; set; }
            public float tempLag13 { get; set; }
            public float tempLag14 { get; set; }
            public float tempLag15 { get; set; }
            public float tempLag16 { get; set; }
            public float tempLag17 { get; set; }
            public float tempLag18 { get; set; }
            public float tempLag19 { get; set; }
            public float tempLag20 { get; set; }
            public float tempLag21 { get; set; }
            public float tempLag22 { get; set; }
            public float tempLag23 { get; set; }
            public float tempLag24 { get; set; }
            public float tempLag25 { get; set; }
            public float tempLag26 { get; set; }
            public float tempLag27 { get; set; }
            public float tempLag28 { get; set; }
            public float tempLag29 { get; set; }
            public float tempLag30 { get; set; }
            public float tempLag31 { get; set; }
            public float tempLag32 { get; set; }
            public float tempLag33 { get; set; }
            public float tempLag34 { get; set; }
            public float tempLag35 { get; set; }
            public float tempLag36 { get; set; }
            public float tempLag37 { get; set; }
            public float tempLag38 { get; set; }
            public float tempLag39 { get; set; }
            public float tempLag40 { get; set; }
            public float tempLag41 { get; set; }
            public float tempLag42 { get; set; }
            public float tempLag43 { get; set; }
            public float tempLag44 { get; set; }
            public float tempLag45 { get; set; }
            public float tempLag46 { get; set; }
            public float tempLag47 { get; set; }
            public float tempLag48 { get; set; }
            public float tempLag49 { get; set; }
            public float tempLag50 { get; set; }
            public float tempLag51 { get; set; }
            public float tempLag52 { get; set; }
            public float tempLag53 { get; set; }
            public float tempLag54 { get; set; }
            public float tempLag55 { get; set; }
            public float tempLag56 { get; set; }
            public float tempLag57 { get; set; }
            public float tempLag58 { get; set; }
            public float tempLag59 { get; set; }
            public float tempLag60 { get; set; }
            public float tempLag61 { get; set; }
            public float tempLag62 { get; set; }
            public float tempLag63 { get; set; }
            public float tempLag64 { get; set; }
            public float tempLag65 { get; set; }
            public float tempLag66 { get; set; }
            public float tempLag67 { get; set; }
            public float tempLag68 { get; set; }
            public float tempLag69 { get; set; }
            public float tempLag70 { get; set; }
            public float tempLag71 { get; set; }
            public float tempLag72 { get; set; }
            public float tempLag73 { get; set; }
            public float tempLag74 { get; set; }
            public float tempLag75 { get; set; }
            public float tempLag76 { get; set; }
            public float tempLag77 { get; set; }
            public float tempLag78 { get; set; }
            public float tempLag79 { get; set; }
            public float tempLag80 { get; set; }
            public float tempLag81 { get; set; }
            public float tempLag82 { get; set; }
            public float tempLag83 { get; set; }
            public float tempLag84 { get; set; }
            public float tempLag85 { get; set; }
            public float tempLag86 { get; set; }
            public float tempLag87 { get; set; }
            public float tempLag88 { get; set; }
            public float tempLag89 { get; set; }
            public float tempLag90 { get; set; }
            public float tempLag91 { get; set; }
            public float tempLag92 { get; set; }
            public float tempLag93 { get; set; }
            public float tempLag94 { get; set; }
            public float tempLag95 { get; set; }
            public float tempLag96 { get; set; }
            public float tempLag97 { get; set; }
            public float tempLag98 { get; set; }
            public float tempLag99 { get; set; }
            public float tempLag100 { get; set; }
            public float tempLag101 { get; set; }
            public float tempLag102 { get; set; }
            public float tempLag103 { get; set; }
            public float tempLag104 { get; set; }
            public float tempLag105 { get; set; }
            public float tempLag106 { get; set; }
            public float tempLag107 { get; set; }
            public float tempLag108 { get; set; }
            public float tempLag109 { get; set; }
            public float tempLag110 { get; set; }
            public float tempLag111 { get; set; }
            public float tempLag112 { get; set; }
            public float tempLag113 { get; set; }
            public float tempLag114 { get; set; }
            public float tempLag115 { get; set; }
            public float tempLag116 { get; set; }
            public float tempLag117 { get; set; }
            public float tempLag118 { get; set; }
            public float tempLag119 { get; set; }
            public float tempLag120 { get; set; }
            public float tempLag121 { get; set; }
            public float tempLag122 { get; set; }
            public float tempLag123 { get; set; }
            public float tempLag124 { get; set; }
            public float tempLag125 { get; set; }
            public float tempLag126 { get; set; }
            public float tempLag127 { get; set; }
            public float tempLag128 { get; set; }
            public float tempLag129 { get; set; }
            public float tempLag130 { get; set; }
            public float tempLag131 { get; set; }
            public float tempLag132 { get; set; }
            public float tempLag133 { get; set; }
            public float tempLag134 { get; set; }
            public float tempLag135 { get; set; }
            public float tempLag136 { get; set; }
            public float tempLag137 { get; set; }
            public float tempLag138 { get; set; }
            public float tempLag139 { get; set; }
            public float tempLag140 { get; set; }
            public float tempLag141 { get; set; }
            public float tempLag142 { get; set; }
            public float tempLag143 { get; set; }
            public float tempLag144 { get; set; }
            public float tempLag145 { get; set; }
            public float tempLag146 { get; set; }
            public float tempLag147 { get; set; }
            public float tempLag148 { get; set; }
            public float tempLag149 { get; set; }
            public float tempLag150 { get; set; }
            public float tempLag151 { get; set; }
            public float tempLag152 { get; set; }
            public float tempLag153 { get; set; }
            public float tempLag154 { get; set; }
            public float tempLag155 { get; set; }
            public float tempLag156 { get; set; }
            public float tempLag157 { get; set; }
            public float tempLag158 { get; set; }
            public float tempLag159 { get; set; }
            public float tempLag160 { get; set; }
            public float tempLag161 { get; set; }
            public float tempLag162 { get; set; }
            public float tempLag163 { get; set; }
            public float tempLag164 { get; set; }
            public float tempLag165 { get; set; }
            public float tempLag166 { get; set; }
            public float tempLag167 { get; set; }
            public float tempLag168 { get; set; }
            public float tempLag169 { get; set; }
            public float tempLag170 { get; set; }
            public float tempLag171 { get; set; }
            public float tempLag172 { get; set; }
            public float tempLag173 { get; set; }
            public float tempLag174 { get; set; }
            public float tempLag175 { get; set; }
            public float tempLag176 { get; set; }
            public float tempLag177 { get; set; }
            public float tempLag178 { get; set; }
            public float tempLag179 { get; set; }
            public float tempLag180 { get; set; }
            public float tempLag181 { get; set; }
            public float tempLag182 { get; set; }
            public float tempLag183 { get; set; }
            public float tempLag184 { get; set; }
            public float tempLag185 { get; set; }
            public float tempLag186 { get; set; }
            public float tempLag187 { get; set; }
            public float tempLag188 { get; set; }
            public float tempLag189 { get; set; }
            public float tempLag190 { get; set; }
            public float tempLag191 { get; set; }
            public float tempLag192 { get; set; }
            public float tempLag193 { get; set; }
            public float tempLag194 { get; set; }
            public float tempLag195 { get; set; }
            public float tempLag196 { get; set; }
            public float tempLag197 { get; set; }
            public float tempLag198 { get; set; }
            public float tempLag199 { get; set; }
            public float tempLag200 { get; set; }
            public float tempLag201 { get; set; }
            public float tempLag202 { get; set; }
            public float tempLag203 { get; set; }
            public float tempLag204 { get; set; }
            public float tempLag205 { get; set; }
            public float tempLag206 { get; set; }
            public float tempLag207 { get; set; }
            public float tempLag208 { get; set; }
            public float tempLag209 { get; set; }
            public float tempLag210 { get; set; }
            public float tempLag211 { get; set; }
            public float tempLag212 { get; set; }
            public float tempLag213 { get; set; }
            public float tempLag214 { get; set; }
            public float tempLag215 { get; set; }
            public float tempLag216 { get; set; }
            public float tempLag217 { get; set; }
            public float tempLag218 { get; set; }
            public float tempLag219 { get; set; }
            public float tempLag220 { get; set; }
            public float tempLag221 { get; set; }
            public float tempLag222 { get; set; }
            public float tempLag223 { get; set; }
            public float tempLag224 { get; set; }
            public float tempLag225 { get; set; }
            public float tempLag226 { get; set; }
            public float tempLag227 { get; set; }
            public float tempLag228 { get; set; }
            public float tempLag229 { get; set; }
            public float tempLag230 { get; set; }
            public float tempLag231 { get; set; }
            public float tempLag232 { get; set; }
            public float tempLag233 { get; set; }
            public float tempLag234 { get; set; }
            public float tempLag235 { get; set; }
            public float tempLag236 { get; set; }
            public float tempLag237 { get; set; }
            public float tempLag238 { get; set; }
            public float tempLag239 { get; set; }
            public float tempLag240 { get; set; }
            public float tempLag241 { get; set; }
            public float tempLag242 { get; set; }
            public float tempLag243 { get; set; }
            public float tempLag244 { get; set; }
            public float tempLag245 { get; set; }
            public float tempLag246 { get; set; }
            public float tempLag247 { get; set; }
            public float tempLag248 { get; set; }
            public float tempLag249 { get; set; }
            public float tempLag250 { get; set; }
            public float tempLag251 { get; set; }
            public float tempLag252 { get; set; }
            public float tempLag253 { get; set; }
            public float tempLag254 { get; set; }
            public float tempLag255 { get; set; }
            public float tempLag256 { get; set; }
            public float tempLag257 { get; set; }
            public float tempLag258 { get; set; }
            public float tempLag259 { get; set; }
            public float tempLag260 { get; set; }
            public float tempLag261 { get; set; }
            public float tempLag262 { get; set; }
            public float tempLag263 { get; set; }
            public float tempLag264 { get; set; }
            public float tempLag265 { get; set; }
            public float tempLag266 { get; set; }
            public float tempLag267 { get; set; }
            public float tempLag268 { get; set; }
            public float tempLag269 { get; set; }
            public float tempLag270 { get; set; }
            public float tempLag271 { get; set; }
            public float tempLag272 { get; set; }
            public float tempLag273 { get; set; }
            public float tempLag274 { get; set; }
            public float tempLag275 { get; set; }
            public float tempLag276 { get; set; }
            public float tempLag277 { get; set; }
            public float tempLag278 { get; set; }
            public float tempLag279 { get; set; }
            public float tempLag280 { get; set; }
            public float tempLag281 { get; set; }
            public float tempLag282 { get; set; }
            public float tempLag283 { get; set; }
            public float tempLag284 { get; set; }
            public float tempLag285 { get; set; }
            public float tempLag286 { get; set; }
            public float tempLag287 { get; set; }
            public float tempLag288 { get; set; }
            public float tempLag289 { get; set; }
            public float tempLag290 { get; set; }
            public float tempLag291 { get; set; }
            public float tempLag292 { get; set; }
            public float tempLag293 { get; set; }
            public float tempLag294 { get; set; }
            public float tempLag295 { get; set; }
            public float tempLag296 { get; set; }
            public float tempLag297 { get; set; }
            public float tempLag298 { get; set; }
            public float tempLag299 { get; set; }
            public float tempLag300 { get; set; }
            public float tempLag301 { get; set; }
            public float tempLag302 { get; set; }
            public float tempLag303 { get; set; }
            public float tempLag304 { get; set; }
            public float tempLag305 { get; set; }
            public float tempLag306 { get; set; }
            public float tempLag307 { get; set; }
            public float tempLag308 { get; set; }
            public float tempLag309 { get; set; }
            public float tempLag310 { get; set; }
            public float tempLag311 { get; set; }
            public float tempLag312 { get; set; }
            public float tempLag313 { get; set; }
            public float tempLag314 { get; set; }
            public float tempLag315 { get; set; }
            public float tempLag316 { get; set; }
            public float tempLag317 { get; set; }
            public float tempLag318 { get; set; }
            public float tempLag319 { get; set; }
            public float tempLag320 { get; set; }
            public float tempLag321 { get; set; }
            public float tempLag322 { get; set; }
            public float tempLag323 { get; set; }
            public float tempLag324 { get; set; }
            public float tempLag325 { get; set; }
            public float tempLag326 { get; set; }
            public float tempLag327 { get; set; }
            public float tempLag328 { get; set; }
            public float tempLag329 { get; set; }
            public float tempLag330 { get; set; }
            public float tempLag331 { get; set; }
            public float tempLag332 { get; set; }
            public float tempLag333 { get; set; }
            public float tempLag334 { get; set; }
            public float tempLag335 { get; set; }
            public float tempLag336 { get; set; }
            public float tempLag337 { get; set; }
            public float tempLag338 { get; set; }
            public float tempLag339 { get; set; }
            public float tempLag340 { get; set; }
            public float tempLag341 { get; set; }
            public float tempLag342 { get; set; }
            public float tempLag343 { get; set; }
            public float tempLag344 { get; set; }
            public float tempLag345 { get; set; }
            public float tempLag346 { get; set; }
            public float tempLag347 { get; set; }
            public float tempLag348 { get; set; }
            public float tempLag349 { get; set; }
            public float tempLag350 { get; set; }
            public float tempLag351 { get; set; }
            public float tempLag352 { get; set; }
            public float tempLag353 { get; set; }
            public float tempLag354 { get; set; }
            public float tempLag355 { get; set; }
            public float tempLag356 { get; set; }
            public float tempLag357 { get; set; }
            public float tempLag358 { get; set; }
            public float tempLag359 { get; set; }
            public float tempLag360 { get; set; }
            public float tempLag361 { get; set; }
            public float tempLag362 { get; set; }
            public float tempLag363 { get; set; }
            public float tempLag364 { get; set; }
            public float tempLag365 { get; set; }
            public float tempLag366 { get; set; }
            public float tempLag367 { get; set; }
            public float tempLag368 { get; set; }
            public float tempLag369 { get; set; }
            public float tempLag370 { get; set; }
            public float tempLag371 { get; set; }
            public float tempLag372 { get; set; }
            public float tempLag373 { get; set; }
            public float tempLag374 { get; set; }
            public float tempLag375 { get; set; }
            public float tempLag376 { get; set; }
            public float tempLag377 { get; set; }
            public float tempLag378 { get; set; }
            public float tempLag379 { get; set; }
            public float tempLag380 { get; set; }
            public float tempLag381 { get; set; }
            public float tempLag382 { get; set; }
            public float tempLag383 { get; set; }
            public float tempLag384 { get; set; }
            public float tempLag385 { get; set; }
            public float tempLag386 { get; set; }
            public float tempLag387 { get; set; }
            public float tempLag388 { get; set; }
            public float tempLag389 { get; set; }
            public float tempLag390 { get; set; }
            public float tempLag391 { get; set; }
            public float tempLag392 { get; set; }
            public float tempLag393 { get; set; }
            public float tempLag394 { get; set; }
            public float tempLag395 { get; set; }
            public float tempLag396 { get; set; }
            public float tempLag397 { get; set; }
            public float tempLag398 { get; set; }
            public float tempLag399 { get; set; }
            public float tempLag400 { get; set; }
            public float tempLag401 { get; set; }
            public float tempLag402 { get; set; }
            public float tempLag403 { get; set; }
            public float tempLag404 { get; set; }
            public float tempLag405 { get; set; }
            public float tempLag406 { get; set; }
            public float tempLag407 { get; set; }
            public float tempLag408 { get; set; }
            public float tempLag409 { get; set; }
            public float tempLag410 { get; set; }
            public float tempLag411 { get; set; }
            public float tempLag412 { get; set; }
            public float tempLag413 { get; set; }
            public float tempLag414 { get; set; }
            public float tempLag415 { get; set; }
            public float tempLag416 { get; set; }
            public float tempLag417 { get; set; }
            public float tempLag418 { get; set; }
            public float tempLag419 { get; set; }
            public float tempLag420 { get; set; }
            public float tempLag421 { get; set; }
            public float tempLag422 { get; set; }
            public float tempLag423 { get; set; }
            public float tempLag424 { get; set; }
            public float tempLag425 { get; set; }
            public float tempLag426 { get; set; }
            public float tempLag427 { get; set; }
            public float tempLag428 { get; set; }
            public float tempLag429 { get; set; }
            public float tempLag430 { get; set; }
            public float tempLag431 { get; set; }
            public float tempLag432 { get; set; }
            public float tempLag433 { get; set; }
            public float tempLag434 { get; set; }
            public float tempLag435 { get; set; }
            public float tempLag436 { get; set; }
            public float tempLag437 { get; set; }
            public float tempLag438 { get; set; }
            public float tempLag439 { get; set; }
            public float tempLag440 { get; set; }
            public float tempLag441 { get; set; }
            public float tempLag442 { get; set; }
            public float tempLag443 { get; set; }
            public float tempLag444 { get; set; }
            public float tempLag445 { get; set; }
            public float tempLag446 { get; set; }
            public float tempLag447 { get; set; }
            public float tempLag448 { get; set; }
            public float tempLag449 { get; set; }
            public float tempLag450 { get; set; }
            public float tempLag451 { get; set; }
            public float tempLag452 { get; set; }
            public float tempLag453 { get; set; }
            public float tempLag454 { get; set; }
            public float tempLag455 { get; set; }
            public float tempLag456 { get; set; }
            public float tempLag457 { get; set; }
            public float tempLag458 { get; set; }
            public float tempLag459 { get; set; }
            public float tempLag460 { get; set; }
            public float tempLag461 { get; set; }
            public float tempLag462 { get; set; }
            public float tempLag463 { get; set; }
            public float tempLag464 { get; set; }
            public float tempLag465 { get; set; }
            public float tempLag466 { get; set; }
            public float tempLag467 { get; set; }
            public float tempLag468 { get; set; }
            public float tempLag469 { get; set; }
            public float tempLag470 { get; set; }
            public float tempLag471 { get; set; }
            public float tempLag472 { get; set; }
            public float tempLag473 { get; set; }
            public float tempLag474 { get; set; }
            public float tempLag475 { get; set; }
            public float tempLag476 { get; set; }
            public float tempLag477 { get; set; }
            public float tempLag478 { get; set; }
            public float tempLag479 { get; set; }
            public float tempLag480 { get; set; }
            public float tempLag481 { get; set; }
            public float tempLag482 { get; set; }
            public float tempLag483 { get; set; }
            public float tempLag484 { get; set; }
            public float tempLag485 { get; set; }
            public float tempLag486 { get; set; }
            public float tempLag487 { get; set; }
            public float tempLag488 { get; set; }
            public float tempLag489 { get; set; }
            public float tempLag490 { get; set; }
            public float tempLag491 { get; set; }
            public float tempLag492 { get; set; }
            public float tempLag493 { get; set; }
            public float tempLag494 { get; set; }
            public float tempLag495 { get; set; }
            public float tempLag496 { get; set; }
            public float tempLag497 { get; set; }
            public float tempLag498 { get; set; }
            public float tempLag499 { get; set; }
            public float tempLag500 { get; set; }
            public float tempLag501 { get; set; }
            public float tempLag502 { get; set; }
            public float tempLag503 { get; set; }
            public float tempLag504 { get; set; }
            public float tempLag505 { get; set; }
            public float tempLag506 { get; set; }
            public float tempLag507 { get; set; }
            public float tempLag508 { get; set; }
            public float tempLag509 { get; set; }
            public float tempLag510 { get; set; }
            public float tempLag511 { get; set; }
            public float tempLag512 { get; set; }
            public float tempLag513 { get; set; }
            public float tempLag514 { get; set; }
            public float tempLag515 { get; set; }
            public float tempLag516 { get; set; }
            public float tempLag517 { get; set; }
            public float tempLag518 { get; set; }
            public float tempLag519 { get; set; }
            public float tempLag520 { get; set; }
            public float tempLag521 { get; set; }
            public float tempLag522 { get; set; }
            public float tempLag523 { get; set; }
            public float tempLag524 { get; set; }
            public float tempLag525 { get; set; }
            public float tempLag526 { get; set; }
            public float tempLag527 { get; set; }
            public float tempLag528 { get; set; }
            public float tempLag529 { get; set; }
            public float tempLag530 { get; set; }
            public float tempLag531 { get; set; }
            public float tempLag532 { get; set; }
            public float tempLag533 { get; set; }
            public float tempLag534 { get; set; }
            public float tempLag535 { get; set; }
            public float tempLag536 { get; set; }
            public float tempLag537 { get; set; }
            public float tempLag538 { get; set; }
            public float tempLag539 { get; set; }
            public float tempLag540 { get; set; }
            public float tempLag541 { get; set; }
            public float tempLag542 { get; set; }
            public float tempLag543 { get; set; }
            public float tempLag544 { get; set; }
            public float tempLag545 { get; set; }
            public float tempLag546 { get; set; }
            public float tempLag547 { get; set; }
            public float tempLag548 { get; set; }
            public float tempLag549 { get; set; }
            public float tempLag550 { get; set; }
            public float tempLag551 { get; set; }
            public float tempLag552 { get; set; }
            public float tempLag553 { get; set; }
            public float tempLag554 { get; set; }
            public float tempLag555 { get; set; }
            public float tempLag556 { get; set; }
            public float tempLag557 { get; set; }
            public float tempLag558 { get; set; }
            public float tempLag559 { get; set; }
            public float tempLag560 { get; set; }
            public float tempLag561 { get; set; }
            public float tempLag562 { get; set; }
            public float tempLag563 { get; set; }
            public float tempLag564 { get; set; }
            public float tempLag565 { get; set; }
            public float tempLag566 { get; set; }
            public float tempLag567 { get; set; }
            public float tempLag568 { get; set; }
            public float tempLag569 { get; set; }
            public float tempLag570 { get; set; }
            public float tempLag571 { get; set; }
            public float tempLag572 { get; set; }
            public float tempLag573 { get; set; }
            public float tempLag574 { get; set; }
            public float tempLag575 { get; set; }
            public float tempLag576 { get; set; }



            //public float heaterOnLast5Minutes { get; set; }
            //public float heaterOnLast10Minutes { get; set; }
            //public float heaterOnLast15Minutes { get; set; }
            //public float heaterOnLast30Minutes { get; set; }
            //public float heaterOnLastHour { get; set; }
            //public float heaterOnLast2Hours { get; set; }
            //public float heaterOnLast4Hours { get; set; }
            //public float heaterOnLast8Hours { get; set; }
            //public float heaterOnLast12Hours { get; set; }
            //public float heaterOnLast24Hours { get; set; }
        }

        public class OutputData
        {
            [ColumnName("Score")]
            public float temperature { get; set; }
        }
    }
}
